# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: VoiceToText.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='VoiceToText.proto',
  package='VoiceToText',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11VoiceToText.proto\x12\x0bVoiceToText\"\x1b\n\x0bTextRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x1c\n\x0c\x63ommand_list\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t2I\n\x04Text\x12\x41\n\x08ShowText\x12\x18.VoiceToText.TextRequest\x1a\x19.VoiceToText.command_list\"\x00\x62\x06proto3')
)




_TEXTREQUEST = _descriptor.Descriptor(
  name='TextRequest',
  full_name='VoiceToText.TextRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='VoiceToText.TextRequest.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=61,
)


_COMMAND_LIST = _descriptor.Descriptor(
  name='command_list',
  full_name='VoiceToText.command_list',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='VoiceToText.command_list.data', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=91,
)

DESCRIPTOR.message_types_by_name['TextRequest'] = _TEXTREQUEST
DESCRIPTOR.message_types_by_name['command_list'] = _COMMAND_LIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TextRequest = _reflection.GeneratedProtocolMessageType('TextRequest', (_message.Message,), dict(
  DESCRIPTOR = _TEXTREQUEST,
  __module__ = 'VoiceToText_pb2'
  # @@protoc_insertion_point(class_scope:VoiceToText.TextRequest)
  ))
_sym_db.RegisterMessage(TextRequest)

command_list = _reflection.GeneratedProtocolMessageType('command_list', (_message.Message,), dict(
  DESCRIPTOR = _COMMAND_LIST,
  __module__ = 'VoiceToText_pb2'
  # @@protoc_insertion_point(class_scope:VoiceToText.command_list)
  ))
_sym_db.RegisterMessage(command_list)



_TEXT = _descriptor.ServiceDescriptor(
  name='Text',
  full_name='VoiceToText.Text',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=93,
  serialized_end=166,
  methods=[
  _descriptor.MethodDescriptor(
    name='ShowText',
    full_name='VoiceToText.Text.ShowText',
    index=0,
    containing_service=None,
    input_type=_TEXTREQUEST,
    output_type=_COMMAND_LIST,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TEXT)

DESCRIPTOR.services_by_name['Text'] = _TEXT

# @@protoc_insertion_point(module_scope)
