# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import VoiceToText_pb2 as VoiceToText__pb2


class TextStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ShowText = channel.unary_unary(
        '/VoiceToText.Text/ShowText',
        request_serializer=VoiceToText__pb2.TextRequest.SerializeToString,
        response_deserializer=VoiceToText__pb2.command_list.FromString,
        )


class TextServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ShowText(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TextServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ShowText': grpc.unary_unary_rpc_method_handler(
          servicer.ShowText,
          request_deserializer=VoiceToText__pb2.TextRequest.FromString,
          response_serializer=VoiceToText__pb2.command_list.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'VoiceToText.Text', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
