// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VoiceToText.proto

package io.grpc.VoiceToText;

public interface command_listOrBuilder extends
    // @@protoc_insertion_point(interface_extends:VoiceToText.command_list)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string data = 1;</code>
   */
  String getData();
  /**
   * <code>string data = 1;</code>
   */
  com.google.protobuf.ByteString
      getDataBytes();
}
