// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VoiceToText.proto

package io.grpc.VoiceToText;

public interface TextRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:VoiceToText.TextRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string text = 1;</code>
   */
  String getText();
  /**
   * <code>string text = 1;</code>
   */
  com.google.protobuf.ByteString
      getTextBytes();
}
