// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VoiceToText.proto

package io.grpc.VoiceToText;

public final class VoiceToTextProto {
  private VoiceToTextProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_VoiceToText_TextRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_VoiceToText_TextRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_VoiceToText_command_list_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_VoiceToText_command_list_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\021VoiceToText.proto\022\013VoiceToText\"\033\n\013Text" +
      "Request\022\014\n\004text\030\001 \001(\t\"\034\n\014command_list\022\014\n" +
      "\004data\030\001 \001(\t2I\n\004Text\022A\n\010ShowText\022\030.VoiceT" +
      "oText.TextRequest\032\031.VoiceToText.command_" +
      "list\"\000B\'\n\013VoiceToTextB\020VoiceToTextProtoP" +
      "\001\242\002\003HLWb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_VoiceToText_TextRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_VoiceToText_TextRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_VoiceToText_TextRequest_descriptor,
        new String[] { "Text", });
    internal_static_VoiceToText_command_list_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_VoiceToText_command_list_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_VoiceToText_command_list_descriptor,
        new String[] { "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
